### ISSUE TITLE
code refaktörün benden gelsin 

### ISSUE THREAD

**Issue by tufan35** [elifdilan/Csharp-Exercises#1]
namespace NumberGuessingGame
{
    class Program
    {
        static void Main(string[] args)
        {
            var name = Console.ReadLine();
            Console.WriteLine("Welcome to Number Guessing Game, {0}!", name);

            var number = new Random().Next(1, 10);
            int guess = 0;

            while (guess != number)
            {
                guess++;
                Console.WriteLine("Please guess a number from 1 to 10: ");
                guess = int.Parse(Console.ReadLine());

                if (guess < number)
                {
                    Console.WriteLine("Your guess is too low.");
                }
                else if (guess > number)
                {
                    Console.WriteLine("Your guess is too high.");
                }
                else
                {
                    Console.WriteLine("Congratulations! You guessed the number in {0} guesses.", guess);
                    break;
                }
            }
        }
    }
}

**Comment by elifdilan** [comment]
Teşekkürler :)
